name: pizzaapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:  
  flutter:
    sdk: flutter
  flutter_dialogs: ^3.0.0
  google_maps_flutter: ^2.5.3
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  logger: ^2.0.2+1
  provider: ^6.1.1
  foundation: ^0.0.5
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  flutter_credit_card: ^4.0.1
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/photo/
