// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY54qRvCUElyl_P2HhqUUWrNQxunb5CHM',
    appId: '1:955012433071:web:10ae3ee1f0f7e3391bc05a',
    messagingSenderId: '955012433071',
    projectId: 'pizzaapp-3fc46',
    authDomain: 'pizzaapp-3fc46.firebaseapp.com',
    storageBucket: 'pizzaapp-3fc46.appspot.com',
    measurementId: 'G-XYNB88B2NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsSOmfTbCIMPB2Jw2YUsMA1jvVn6BxfOQ',
    appId: '1:955012433071:android:960e1e247d1d384c1bc05a',
    messagingSenderId: '955012433071',
    projectId: 'pizzaapp-3fc46',
    storageBucket: 'pizzaapp-3fc46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX30EmRUpd7a0sHLHOUe2bxhrl8KWhyko',
    appId: '1:955012433071:ios:4eb8ef6f63174b9e1bc05a',
    messagingSenderId: '955012433071',
    projectId: 'pizzaapp-3fc46',
    storageBucket: 'pizzaapp-3fc46.appspot.com',
    iosBundleId: 'com.example.pizzaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX30EmRUpd7a0sHLHOUe2bxhrl8KWhyko',
    appId: '1:955012433071:ios:2b6b5b1db068f49d1bc05a',
    messagingSenderId: '955012433071',
    projectId: 'pizzaapp-3fc46',
    storageBucket: 'pizzaapp-3fc46.appspot.com',
    iosBundleId: 'com.example.pizzaapp.RunnerTests',
  );
}
